spring:
  application:
    name: prototype

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/finhubDB
    username: postgres
    password: NagaSai@2025
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8080/realms/Finhub
          jwk-set-uri: http://host.docker.internal:8080/realms/Finhub/protocol/openid-connect/certs

server:
  port: 8081

logging:
  level:
    com.finhub.prototype: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.filter.OncePerRequestFilter: DEBUG
    org.hibernate.SQL: DEBUG
    root: INFO
